
CREATE DATABASE [Schema24HeureDuCode]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Schema24HeureDuCode', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\Schema24HeureDuCode.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Schema24HeureDuCode_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\Schema24HeureDuCode.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Schema24HeureDuCode] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Schema24HeureDuCode].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Schema24HeureDuCode] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET ARITHABORT OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Schema24HeureDuCode] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Schema24HeureDuCode] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Schema24HeureDuCode] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Schema24HeureDuCode] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Schema24HeureDuCode] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET RECOVERY FULL 
GO
ALTER DATABASE [Schema24HeureDuCode] SET  MULTI_USER 
GO
ALTER DATABASE [Schema24HeureDuCode] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Schema24HeureDuCode] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Schema24HeureDuCode] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Schema24HeureDuCode] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Schema24HeureDuCode] SET READ_WRITE 
GO
